### ISSUE TITLE
Feature/bug

### ISSUE THREAD

**Issue by Staegrin** [oldjunyi/NoMobSpawningOnTrees#1]
Could it be made possible for mobs to not spawn on Minefactory reloaded rubber tree logs?

**Comment by oldjunyi** [comment]
By default, mobs will not spawn on all types of logs, including in other mods:
![a](https://cloud.githubusercontent.com/assets/641817/13354698/ae064736-dcd7-11e5-8bdc-7c1d320d011c.png)

**Comment by Staegrin** [comment]
Why do mobs then spawn in the rubber trees?
![2016-02-26_16 07 45](https://cloud.githubusercontent.com/assets/8494635/13355960/4699ea00-dca3-11e5-90fa-23d0733b524c.png)
![2016-02-26_16 08 13](https://cloud.githubusercontent.com/assets/8494635/13355962/484e7bfe-dca3-11e5-8424-3e250ac5bc76.png)
There are also 2 versions of the logs. The ones naturally grown and the ones placed. Not sure if this would make any difference.

**Comment by Staegrin** [comment]
![2016-02-26_16 11 01](https://cloud.githubusercontent.com/assets/8494635/13356021/999c888e-dca3-11e5-8d7e-b453c89b1517.png)
2 zombies and 2 skeletons a few minuets after my last post.

**Comment by oldjunyi** [comment]
OK, I will check it.

**Comment by oldjunyi** [comment]
Fixed. Get new version here: http://minecraft.curseforge.com/projects/no-mob-spawning-on-trees

**Comment by Staegrin** [comment]
Yes, latest version has fixed the mob spawning.
