### ISSUE TITLE
Sky visible tag

### ISSUE THREAD

**Issue by andrewminer** [oldjunyi/NoMobSpawningOnTrees#10]
It would be great to have a tag which allows you to spawn / not spawn entities based upon whether the sky is visible from that block (e.g., `mobtype:monster & sky:visible`).

**Comment by oldjunyi** [comment]
Have you tried light level tag with skylight option?

**Comment by andrewminer** [comment]
I was trying to prevent mobs spawning on the surface.  So, I tried `light:0-15,sky`, but it wasn't clear to me whether that did the same thing.  At night, the surface has light level 0 from the sky, and a cave also has light level 0 from the sky, so I didn't think that rule would implement what I want.  I *do* want mobs to spawn in caves... just not on the surface.

**Comment by ChloeDawn** [comment]
@andrewminer sky light level is always 15 on the surface, even at night. use `light:1-15,sky` to prevent surface mob spawns.

**Comment by andrewminer** [comment]
Ah... I didn't realize that, @InsomniaKitten.  Thanks, that will do what I was looking for.
