### ISSUE TITLE
Rules ignored?

### ISSUE THREAD

**Issue by Squaredude** [oldjunyi/NoMobSpawningOnTrees#4]
I've tried using the same rules as I did in the 1.9.4 version, to exclude mobs in the Overworld, but they seem to be ignored.

Rule example: dim:0 & mob:EntityCreeper

Expected result: no more Creepers spawning in the Overworld.

Result: Creepers keep spawning in the Overworld.

I reported this in the mod comments, a few months ago, but maybe reporting it here will be more useful.

**Comment by oldjunyi** [comment]
1.11 version? The entity list changed a bit. Maybe I am using it in a wrong way. Will fix it soon.

## 

姜凯 (Kai Jiang)

在 2016年11月21日，上午12:05，Leonardo <notifications@github.com<mailto:notifications@github.com>> 写道：

I've tried using the same rules as I did in the 1.9.4 version, to exclude mobs in the Overworld, but they seem to be ignored.

Rule example: dim:0 & mob:EntityCreeper

Expected result: no more Creepers spawning in the Overworld.

Result: Creepers keep spawning in the Overworld.

I reported this in the mod comments, a few months ago, but maybe reporting it here will be more useful.

―

**Comment by oldjunyi** [comment]
Oh sorry I did not notice it is 194, will recheck the mod

## 

姜凯 (Kai Jiang)

在 2016年11月21日，上午12:05，Leonardo <notifications@github.com<mailto:notifications@github.com>> 写道：

I've tried using the same rules as I did in the 1.9.4 version, to exclude mobs in the Overworld, but they seem to be ignored.

Rule example: dim:0 & mob:EntityCreeper

Expected result: no more Creepers spawning in the Overworld.

Result: Creepers keep spawning in the Overworld.

I reported this in the mod comments, a few months ago, but maybe reporting it here will be more useful.

―

**Comment by Squaredude** [comment]
(Sorry I forgot to specify versions in my first post.)

Version 1.10.2 is the faulty one.

Version 1.9.4 was working for me. But on the upgrade to the 1.10.2, the same rules stopped working.

**Comment by oldjunyi** [comment]
Fixed. Check https://minecraft.curseforge.com/projects/no-mob-spawning-on-trees/files/2347577 for updated version.

**Comment by Squaredude** [comment]
**Thanks a lot.**

I'm sorry I couldn't reply before, but I just now got free time to test it. I can confirm it's working now.
