### ISSUE TITLE
Rule for Moon Phase?

### ISSUE THREAD

**Issue by Thiana** [oldjunyi/NoMobSpawningOnTrees#5]
Could you please consider adding a rule to adjust spawning based on moon phase? Specifically I'd like to limit spawns during a full moon but increase them during the new moon.

The phases are detailed at http://minecraft.gamepedia.com/Moon, and it looks like you can retrieve the current phase with `world.provider.getMoonPhase`

Thank you :)

**Comment by oldjunyi** [comment]
Cool, will add.

**Comment by oldjunyi** [comment]
Done. Please check https://minecraft.curseforge.com/projects/no-mob-spawning-on-trees

**Comment by Thiana** [comment]
Perfect :) Thanks!
